[project]
name = "de-project-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-bigquery>=1.10.2",
    "dbt-core>=1.10.13",
    "dbt-databricks>=1.10.9",
]
